import { Experience } from 'src/models/experience.model';

export const esperiences: Experience[] = [
    {role: "IT CONSULTANT", company:"C-DEV SA - Luxembourg",description:"Design, develop and execute software solutions to address business issues • Provide architectural blueprints and technical leadership to our IT team • Evaluate and recommend tools, technologies and processes to ensure the highest quality product platform • Collaborate with peer organizations, quality assurance and end users to produce cutting-edge software solutions • Interpret business requirements to articulate the business needs to be addressed Troubleshoot code level problems quickly and efficiently", date:"02/2020 - present"},
    {role: "Software Developer", company:"Cineca Consortium - Italy",description:"Traduct functional and non functional requirements into technical requirements of software product that meet the customer needs. Design and realize Website, API REST and SOAP. Organize functional and unit tests. Design and optimize Database. Write technical documentation", date:"06/2014 - 15/01/2020"},
    {role: "Software Developer", company:"Freelancer",description:"Design, realize, adapt and optimize Web application. Organize functional and unit tests. Design and optimize Database. Write technical documentation", date:"04/2013 – 06/2014"},
    {role: "Project Engineer", company:"Bisol S.r.l - Italy",description:"Develop projects: evalution of costs and deadlines, technical support to customers and sales manager. Monitore process and requests changes. Set priorities", date:"04/2012 – 04/2013"},
    {role: "Trainee", company:"IMPAR S.r.l - Italy",description:"Design electrical and refrigeration systems", date:"03/2012 – 04/2012"},
    {role: "Photovoltaic systems designer", company:"GP Service s.r.l - Italy",description:"Design and configure photovoltaic installation systems", date:"06/2011 – 09/2011"},
    {role: "Computer assistance technician", company:"TECNOFORM System s.r.l - Italy",description:"Install and troubleshoot workstation and hardware peripherals. Install and Update Applications", date:"10/2010 – 01/2011"},
    {role: "Computer Numerical Control (CNC) Programmer", company:"TRW Motor - Italy",description:"Ensure accuracy of instructions set.Monitor all CNC program", date:"05/2008 – 08/2008"},
    {role: "Systems and Network Technician", company:"University of Ferrara",description:"Install and oversee computer equipment and software on the university laboratory. Manage network, domain, group, account and security. Support of desktop users.", date:"09/2005 – 05/2006"}
];