import { Skill } from 'src/models/skill.model';

export const skills: Skill[] = [
    {type:"programming-languages",description:"html5\"></i>"},
    {type:"programming-languages",description:"css3-alt"},
    {type:"programming-languages",description:"js-square"},
    {type:"programming-languages",description:"angular"},
    {type:"programming-languages",description:"react"},
    {type:"programming-languages",description:"node-js"},
    {type:"programming-languages",description:"sass"},
    {type:"programming-languages",description:"less"},
    {type:"programming-languages",description:"wordpress"},
    {type:"programming-languages",description:"npm"},
    {type:"programming-languages",description:"java"},
    {type:"programming-languages",description:"php"},
    {type:"programming-languages",description:"symfony"},
    {type:"workflow",description:"Mobile-First, Responsive Design"},
    {type:"workflow",description:"Cross Functional Teams"},
    {type:"workflow",description:"Agile Development & Scrum"},
    {type:"workflow",description:"Countinuous Delivery, Countinuous Integration"},
    {type:"database",description:"Oracle"},
    {type:"database",description:"Mysql"},
    {type:"database",description:"MongoDb"},
    {type:"database",description:"postgreSql"},
    {type:"develpment-tools",description:"Git"},
    {type:"develpment-tools",description:"Jenkins"},
    {type:"develpment-tools",description:"PhpStorm"},
    {type:"develpment-tools",description:"Eclipse"},
    {type:"develpment-tools",description:"Netbeans"},
    {type:"develpment-tools",description:"Sublime-text"},
    {type:"virtualization",description:"Hyper-V"},
    {type:"virtualization",description:"Vmware"},
    {type:"virtualization",description:"Docker"},
];